const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const COLORS=["#111111","#ffffff","#e53935","#f58220","#ffd43b","#2e9d57","#2878d0","#7b4ab8","#ef5da8","#8b5a2b","#8a8f98","#4b5563"];
const CHALLENGES=["Create a character using only 4 colors.","Create a Sprite with a special power.","Create 3 frames showing your character walking.","Animate your character jumping.","Create your own original Sprite."];
let S={size:16,frames:[null],current:0,tool:"pencil",color:"#111111",fps:6,loop:true,grid:true,onion:false,previewGrid:false,zoom:1,name:"",type:"Hero",power:""},hist=[],future=[],drawing=false,playing=false,timer=null,pendingTemplate=false;
const blank=n=>Array.from({length:n},()=>Array(n).fill(null)),copy=a=>a.map(r=>r.slice());
function snap(){return JSON.stringify(S.frames)} function remember(){hist.push(snap());if(hist.length>40)hist.shift();future=[]}
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1700)}
function color(c){S.color=c;$("#color").value=c;$("#swatch").style.background=c;$("#hex").textContent=c.toUpperCase();$$(".sw").forEach(x=>x.classList.toggle("active",x.dataset.c===c))}
function show(id){["welcome","sizes","editor"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==id))}
function renderSize(){let n=S.size;$("#sizePreview").style.backgroundSize=`${160/n}px ${160/n}px` ;$$(".sizes button").forEach(b=>b.classList.toggle("selected",+b.dataset.size===n))}
function draw(ctx,f,cell,ox=0,oy=0){for(let y=0;y<S.size;y++)for(let x=0;x<S.size;x++)if(f[y][x]){ctx.fillStyle=f[y][x];ctx.fillRect(ox+x*cell,oy+y*cell,cell+.5,cell+.5)}}
function renderCanvas(){let c=$("#canvas"),wrap=$("#canvasWrap"),side=Math.min(600,Math.max(230,Math.min(wrap.clientWidth-40,wrap.clientHeight-40)))*S.zoom;c.width=c.height=side;c.style.width=c.style.height=side+"px";let ctx=c.getContext("2d"),cell=side/S.size;ctx.clearRect(0,0,side,side);if(S.onion&&S.current>0){ctx.globalAlpha=.16;draw(ctx,S.frames[S.current-1],cell);ctx.globalAlpha=1}draw(ctx,S.frames[S.current],cell);if(S.grid){ctx.strokeStyle="#5554";ctx.lineWidth=1;for(let i=0;i<=S.size;i++){ctx.beginPath();ctx.moveTo(i*cell,0);ctx.lineTo(i*cell,side);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*cell);ctx.lineTo(side,i*cell);ctx.stroke()}}renderPreview()}
function renderPreview(){let c=$("#preview"),size=Math.min(210,Math.max(100,S.size*8));c.width=c.height=size;draw(c.getContext("2d"),S.frames[S.current],size/S.size);if(S.previewGrid){let x=c.getContext("2d"),cell=size/S.size;x.strokeStyle="#5554";for(let i=0;i<=S.size;i++){x.beginPath();x.moveTo(i*cell,0);x.lineTo(i*cell,size);x.stroke();x.beginPath();x.moveTo(0,i*cell);x.lineTo(size,i*cell);x.stroke()}}}
function renderTimeline(){let t=$("#timeline");t.innerHTML="";S.frames.forEach((f,i)=>{let b=document.createElement("button");b.className="frame"+(i===S.current?" active":"");let c=document.createElement("canvas");c.width=c.height=80;draw(c.getContext("2d"),f,80/S.size);b.append(c);b.insertAdjacentHTML("beforeend",`<span class=num>${i+1}</span>`);b.onclick=()=>{S.current=i;render()};t.append(b)});$("#frameCount").textContent=`Frame ${S.current+1} / ${S.frames.length}`}
function render(){renderCanvas();renderTimeline();$("#canvasLabel").textContent=`${S.size} × ${S.size}`;$("#zoomLabel").textContent=Math.round(S.zoom*100)+"%";$("#spriteName").value=S.name;$("#type").value=S.type;$("#power").value=S.power;$("#loop").checked=S.loop;$("#grid").checked=S.grid;$("#onion").checked=S.onion;color(S.color);renderFPS();updateHint()}
function flood(x,y){let f=S.frames[S.current],old=f[y][x],q=[[x,y]],seen=new Set;if(old===S.color)return;while(q.length){let[a,b]=q.pop(),k=a+","+b;if(seen.has(k)||a<0||b<0||a>=S.size||b>=S.size||f[b][a]!==old)continue;seen.add(k);f[b][a]=S.color;q.push([a+1,b],[a-1,b],[a,b+1],[a,b-1])}}
function paint(e){let c=$("#canvas"),r=c.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/(r.width/S.size)),y=Math.floor((e.clientY-r.top)/(r.height/S.size));if(x<0||y<0||x>=S.size||y>=S.size)return;let f=S.frames[S.current];if(S.tool==="picker"){if(f[y][x])color(f[y][x]);S.tool="pencil";setTools();return}if(S.tool==="fill"){flood(x,y);renderCanvas();return}f[y][x]=S.tool==="eraser"?null:S.color;renderCanvas()}
function setTools(){$$(".tool").forEach(b=>b.classList.toggle("active",b.dataset.tool===S.tool))}
function undo(){if(!hist.length)return;future.push(snap());S.frames=JSON.parse(hist.pop());render()}function redo(){if(!future.length)return;hist.push(snap());S.frames=JSON.parse(future.pop());render()}
function add(dup){remember();S.frames.splice(S.current+1,0,dup?copy(S.frames[S.current]):blank(S.size));S.current++;render()}
function del(){if(S.frames.length<2)return toast("Keep at least one frame.");remember();S.frames.splice(S.current,1);S.current=Math.max(0,S.current-1);render()}
function move(d){let n=S.current+d;if(n<0||n>=S.frames.length)return;remember();[S.frames[S.current],S.frames[n]]=[S.frames[n],S.frames[S.current]];S.current=n;render()}
function template(){let f=blank(S.size),q=S.size/16,rect=(a,b,c,d,col)=>{for(let y=Math.floor(b*q);y<=Math.floor(d*q);y++)for(let x=Math.floor(a*q);x<=Math.floor(c*q);x++)if(x>=0&&y>=0&&x<S.size&&y<S.size)f[y][x]=col};rect(5,3,10,4,"#f58220");rect(4,5,11,10,"#2878d0");rect(5,11,6,14,"#111111");rect(9,11,10,14,"#111111");rect(5,6,6,7,"#fff");rect(9,6,10,7,"#fff");rect(7,8,8,9,"#ffd43b");S.frames[S.current]=f}
function play(){clearInterval(timer);playing=true;$("#play").textContent="⏸ PAUSE";timer=setInterval(()=>{S.current++;if(S.current>=S.frames.length){if(S.loop)S.current=0;else{S.current=S.frames.length-1;stop()}}render()},1000/S.fps)}
function stop(){clearInterval(timer);playing=false;$("#play").textContent="▶ PLAY"}
function renderFPS(){$("#fps").innerHTML=[1,2,4,6,8,12].map(n=>`<button class="${n===S.fps?"active":""}" data-f="${n}">${n}</button>`).join("");$$("#fps button").forEach(b=>b.onclick=()=>{S.fps=+b.dataset.f;if(playing)play();renderFPS()})}
function updateHint(){let e=$("#hint");if(!$("#learn").checked){e.classList.add("hidden");return}let m={pencil:"Pixel: a tiny square that helps us build our digital drawing.",eraser:"Eraser: remove pixels and try again.",fill:"Fill: color a connected area quickly.",picker:"Color Picker: choose a color directly from your Sprite."};e.textContent="💡 "+(m[S.tool]||"Frame: one picture in an animation.");e.classList.remove("hidden")}
function fileDownload(blob,name){let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function name(){return(S.name||"my-sprite").toLowerCase().replace(/[^a-z0-9]+/g,"-")}
function pngBlob(f,scale){let c=document.createElement("canvas");c.width=c.height=S.size*scale;draw(c.getContext("2d"),f,scale);return new Promise(r=>c.toBlob(r,"image/png"))}
async function exportPNG(){fileDownload(await pngBlob(S.frames[S.current],Math.max(4,Math.floor(256/S.size))),name()+"-sprite.png");toast("PNG exported!")}
async function exportFrames(){for(let i=0;i<S.frames.length;i++)fileDownload(await pngBlob(S.frames[i],Math.max(4,Math.floor(256/S.size))),`${name()}-frame-${i+1}.png`);toast("Frames exported!")}
async function exportSheet(){let scale=Math.max(4,Math.floor(256/S.size)),c=document.createElement("canvas");c.width=S.size*scale*S.frames.length;c.height=S.size*scale;let x=c.getContext("2d");S.frames.forEach((f,i)=>draw(x,f,scale,i*S.size*scale,0));c.toBlob(b=>fileDownload(b,name()+"-sprite-sheet.png"),"image/png");toast("Sprite sheet exported!")}
function project(){return JSON.stringify({version:1,canvasWidth:S.size,canvasHeight:S.size,frames:S.frames,fps:S.fps,loop:S.loop,spriteName:S.name,characterType:S.type,specialPower:S.power},null,2)}
function save(){fileDownload(new Blob([project()],{type:"application/json"}),name()+".json");toast("Project saved!")}
function load(file){if(!file)return;let r=new FileReader();r.onload=()=>{try{let p=JSON.parse(r.result);S.size=p.canvasWidth||16;S.frames=p.frames||[blank(S.size)];S.fps=p.fps||6;S.loop=p.loop!==false;S.name=p.spriteName||"";S.type=p.characterType||"Hero";S.power=p.specialPower||"";S.current=0;show("editor");render();toast("Project loaded!")}catch{toast("Could not open this project.")}};r.readAsText(file)}
$$(".sizes button").forEach(b=>b.onclick=()=>{S.size=+b.dataset.size;renderSize()});
$("#startBtn").onclick=()=>show("sizes");$$("[data-start]").forEach(b=>b.onclick=()=>{pendingTemplate=b.dataset.start==="template";show("sizes")});
$("#openLab").onclick=()=>{S.frames=[blank(S.size)];if(pendingTemplate)template();pendingTemplate=false;show("editor");render()};
$("#welcomeFile").onchange=e=>load(e.target.files[0]);$("#openFile").onchange=e=>load(e.target.files[0]);
$("#newBtn").onclick=()=>{S={...S,size:16,frames:[blank(16)],current:0,name:"",power:""};show("sizes");renderSize()};
$("#saveBtn").onclick=save;$("#undo").onclick=undo;$("#redo").onclick=redo;$("#clear").onclick=()=>{remember();S.frames[S.current]=blank(S.size);render()};
$$(".tool").forEach(b=>b.onclick=()=>{S.tool=b.dataset.tool;setTools();updateHint()});
$("#color").oninput=e=>color(e.target.value);$("#saveColor").onclick=()=>{let b=document.createElement("button");b.className="sw";b.style.background=S.color;b.onclick=()=>color(S.color);$("#myColors").append(b)};
$("#grid").onchange=e=>{S.grid=e.target.checked;renderCanvas()};$("#onion").onchange=e=>{S.onion=e.target.checked;renderCanvas()};$("#learn").onchange=updateHint;
$("#zoomIn").onclick=()=>{S.zoom=Math.min(2,S.zoom+.1);renderCanvas()};$("#zoomOut").onclick=()=>{S.zoom=Math.max(.5,S.zoom-.1);renderCanvas()};
$("#previewGrid").onclick=()=>{S.previewGrid=!S.previewGrid;$("#previewGrid").textContent=S.previewGrid?"Grid ON":"Grid OFF";renderPreview()};
$("#play").onclick=()=>playing?stop():play();$("#loop").onchange=e=>S.loop=e.target.checked;
$("#add").onclick=()=>add(false);$("#duplicate").onclick=()=>add(true);$("#delete").onclick=del;$("#left").onclick=()=>move(-1);$("#right").onclick=()=>move(1);
["spriteName","type","power"].forEach(id=>$("#"+id).oninput=e=>S[id==="spriteName"?"name":id==="type"?"type":"power"]=e.target.value);
$("#challengeBtn").onclick=()=>$("#challengeText").textContent=CHALLENGES[Math.floor(Math.random()*CHALLENGES.length)];
$("#templates").innerHTML=["🤖 Robot","🐱 Cat","👽 Alien","🚀 Ship","🦸 Hero","👾 Monster"].map(x=>`<button>${x}</button>`).join("");$$(".templates button").forEach(b=>b.onclick=()=>{remember();template();render();toast("Template added — now make it yours!")});
$("#canvas").onpointerdown=e=>{drawing=true;remember();paint(e);$("#canvas").setPointerCapture(e.pointerId)};$("#canvas").onpointermove=e=>{if(drawing)paint(e)};$("#canvas").onpointerup=()=>drawing=false;$("#canvas").onpointerleave=()=>drawing=false;$("#canvas").oncontextmenu=e=>e.preventDefault();
COLORS.forEach(c=>{let b=document.createElement("button");b.className="sw";b.style.background=c;b.dataset.c=c;b.onclick=()=>color(c);$("#palette").append(b)});color(S.color);
$("#exportBtn").onclick=()=>$("#exportDialog").showModal();$("#helpBtn").onclick=()=>$("#helpDialog").showModal();$$("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).close());
$("#png").onclick=exportPNG;$("#frames").onclick=exportFrames;$("#sheet").onclick=exportSheet;$("#gif").onclick=()=>toast("GIF export requires a GIF encoder library; PNG, frames and sprite sheet are ready.");
document.addEventListener("keydown",e=>{if(["INPUT","SELECT","TEXTAREA"].includes(document.activeElement.tagName))return;let k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&k==="z"){e.preventDefault();e.shiftKey?redo():undo()}else if(k==="p")S.tool="pencil";else if(k==="e")S.tool="eraser";else if(k==="f")S.tool="fill";else if(k==="i")S.tool="picker";setTools()});
window.onresize=()=>!$("#editor").classList.contains("hidden")&&renderCanvas();
renderSize();$("#fps").innerHTML=[1,2,4,6,8,12].map(n=>`<button class="${n===6?"active":""}" data-f="${n}">${n}</button>`).join("");renderFPS();
